# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch<
import torch

# Create random tensor
tensor_rnd = torch.rand(7,7)
tensor_rnd,tensor_rnd.shape

(tensor([[0.2848, 0.6850, 0.6090, 0.1963, 0.8983, 0.2705, 0.2577],
         [0.2149, 0.2408, 0.2903, 0.5966, 0.4048, 0.2574, 0.8936],
         [0.8606, 0.7934, 0.9605, 0.7478, 0.0629, 0.4088, 0.4937],
         [0.9348, 0.1606, 0.1110, 0.6633, 0.1752, 0.7061, 0.7483],
         [0.6471, 0.6087, 0.7137, 0.5212, 0.7117, 0.0812, 0.4212],
         [0.2310, 0.0653, 0.4896, 0.1579, 0.1827, 0.5868, 0.9899],
         [0.4567, 0.8338, 0.6968, 0.1151, 0.9978, 0.3552, 0.0791]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor_rnd_2 = torch.rand(1,7)
# Perform matrix multiplication
result = torch.mm(tensor_rnd,tensor_rnd_2.T)
result, result.shape

(tensor([[1.8025],
         [1.2475],
         [2.2655],
         [1.2150],
         [1.9775],
         [1.0467],
         [2.0272]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_rnd_3 = torch.rand(7,7)
tensor_rnd_4 = torch.rand(1,7)

# Matrix multiply tensors
result = torch.mm(tensor_rnd_3,tensor_rnd_4.T)

result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU

torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)
tensor_rnd_5 = torch.rand(2,3)
# Every time you reset the seed, forces the pseudorandom number generator to start from the begining,
# thats why if we do it here we will get the same results in both cases.
# Usually this type of pseudorandom number generators are continous probability distributions
# and the seed indicates from where to start picking numbers.
#torch.manual_seed(1234)
tensor_rnd_6 = torch.rand(2,3)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU

tensor_on_gpu_5 = tensor_rnd_5.to(device)
tensor_on_gpu_6 = tensor_rnd_6.to(device)

device,tensor_on_gpu_5,tensor_on_gpu_6

('cuda',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
result = torch.mm(tensor_on_gpu_5, tensor_on_gpu_6.T)

result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max = result.max()
# Find min
min = result.min()

print(f'Max: {max} | Min: {min}')

Max: 0.5617256760597229 | Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
argmax = result.argmax()
# Find arg min
argmin = result.argmin()

print(f'Index of Max: {argmax} | Index of Min: {argmin}')

Index of Max: 3 | Index of Min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1,1,1,10)

# Remove single dimensions
squeezed_tensor = tensor.squeeze()

# Print out tensors and their shapes
tensor,tensor.shape,squeezed_tensor,squeezed_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))