In [2]:
# To see specs of the gpu in use
!nvidia-smi

Mon Feb  5 11:51:21 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'2.1.0+cu121'

# Introduction to tensors

Pytorch tensors are created using torch.tensor()

For more information: https://pytorch.org/docs/stable/tensors.html

## Creating tensors

In [4]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# To get the number within a tensor we use item() class method. (Only available with one-elements tensors)

scalar.item()

7

In [14]:
# Vector

vector = torch.tensor([[7,7,7],[7,7,7]])
vector

tensor([[7, 7, 7],
        [7, 7, 7]])

In [15]:
vector.ndim

2

In [16]:
# Check shape of vector

vector.shape

torch.Size([2, 3])

In [17]:
# Matrix

MATRIX = torch.tensor([
    [7,8],
    [9,10]
    ])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
# Check number of dimensions

MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

In [27]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(size=(2,2,2))

random_tensor, random_tensor.dtype

(tensor([[[0.1739, 0.1655],
          [0.1405, 0.1774]],
 
         [[0.1887, 0.3700],
          [0.4536, 0.2294]]]),
 torch.float32)

In [28]:
# Creating a random tensor of size (224,224,3)

random_image_size_tensor = torch.rand(size=(224,224,3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [29]:
# Create a tensor of all zeros

zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [30]:
# Create a tensor of all ones

ones = torch.ones(size = (3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [31]:
# We use torch.arange(), torch.range() is deprecated

#zero_to_ten_deprecated = torch.range(1,10)

# Create a range of values from 1 to 10

zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# We create a tensor of zeros with the shape of another tensor

ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [33]:
# Default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device = None, # defaults to None, which uses the default tensor type
                               requires_grad = False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [35]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)

float_16_tensor.dtype

torch.float16

# Getting information from tensors


In [36]:
# Create a tensor

some_tensor = torch.rand(3,4)

# Find details about it

print(some_tensor)
print(f" \nShape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0617, 0.1654, 0.0136, 0.0472],
        [0.5861, 0.3359, 0.4936, 0.5101],
        [0.3589, 0.2335, 0.4586, 0.2753]])
 
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors (Tensor operations)

## Basic operations


In [37]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor * 10

tensor([10, 20, 30])

In [39]:
# Values inside the tensor don't change until they are reassigned

tensor

tensor([1, 2, 3])

In [40]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [41]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [42]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [43]:
# Its values also remain unchanged

tensor

tensor([1, 2, 3])

In [44]:
# Element-wise multiplication, each element multiplies each equivalent index

tensor * tensor

tensor([1, 4, 9])

## Matrix multiplication


In [45]:
tensor = torch.tensor([1,2,3])

tensor.shape

torch.Size([3])

In [46]:
# Element-wise matrix multiplication

tensor * tensor

tensor([1, 4, 9])

In [47]:
# Matrix multiplication

tensor.matmul(tensor)

tensor(14)

In [48]:
# Another way of matrix multiplication

tensor @ tensor

tensor(14)

In [49]:
# Is faster using the class method than doing it by hand

%%time

# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.23 ms, sys: 0 ns, total: 1.23 ms
Wall time: 1.31 ms


tensor(14)

In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 100 µs, sys: 0 ns, total: 100 µs
Wall time: 104 µs


tensor(14)

# One of the most common errors in deep learning

In [51]:
# Shapes need to be in the right way

tensor_A =  torch.tensor([
    [1,2],
    [3,4],
    [5,6]
], dtype = torch.float32)
tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
], dtype = torch.float32)

torch.matmul(tensor_A, tensor_B) # That will be error, shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
# First we view the two tensors

print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [53]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [54]:
# Operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [55]:
# Use torch.mm() as a shortcut of torch.matmul()
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [62]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Finding the min, max, mean, sum, etc (aggregation)

In [57]:
# First we create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")


Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Same as above but using torch methods

torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

## Positional Min/Max

In [ ]:
tensor = torch.arange(0,100,10)
print(tensor)

# Returns index of max and min values
print(f"\nIndex where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Index where max value occurs: 9
Index where min value occurs: 0


## Change tensor datatype

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# Create a float16 tensor

tensor_float16 = tensor.type(dtype = torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Create an int8 tensor

tensor_int8 = tensor.type(dtype = torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking, squeezing and unsqueezing

In [68]:
# Create a tensor

x = torch.arange(0.,8.)
x, x.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7.]), torch.Size([8]))

In [69]:
# Now we add an extra dimension with reshape

x_reshaped = x.reshape(4,2)
x_reshaped, x_reshaped.shape

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.]]),
 torch.Size([4, 2]))

In [71]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 8)
z, z.shape

(tensor([[0., 1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 8]))

In [73]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 1., 2., 3., 4., 5., 6., 7.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7.]))

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 1., 2., 3., 4., 5., 6., 7.],
        [5., 1., 2., 3., 4., 5., 6., 7.],
        [5., 1., 2., 3., 4., 5., 6., 7.],
        [5., 1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x = torch.arange(1., 8.)
x_reshaped = x.reshape(1, 7)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)

In [75]:
# First we create a tensor

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [76]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [82]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [83]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [86]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [87]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array

tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

Tensor B:
tensor([[0.1336, 0.9666, 0.9754, 0.8474],
        [0.8988, 0.1105, 0.4563, 0.9719],
        [0.3968, 0.1496, 0.4743, 0.9973]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Running tensors on GPUs (and making faster computations)

In [88]:
# Check for GPU

torch.cuda.is_available()

True

In [89]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [90]:
# Count number of devices
torch.cuda.device_count()

1

In [91]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [92]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [93]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')